-- 코드를 입력하세요
SELECT YEAR(o.SALES_DATE) AS YEAR,
        MONTH(o.SALES_DATE) AS MONTH,
        u.GENDER,
        COUNT(DISTINCT u.USER_ID) AS USERS
FROM ONLINE_SALE o
JOIN USER_INFO u ON o.USER_ID = u.USER_ID
WHERE u.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, u.GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC;
        